---
namespace: veeam
name: workshop
version: 1.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>

description: Ansible collection for deploying Veeam workshops on OpenShift

license:
  - GPL-2.0-or-later

tags:
  - veeam
  - kasten
  - openshift
  - workshop

dependencies: {}

build_ignore:
  - .git
  - .gitignore
  - .DS_Store
